import Link from "next/link";

export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen bg-[#121212] text-zinc-300 py-16 px-6 md:px-12 lg:px-24 font-light">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="text-zinc-500 hover:text-white transition-colors mb-12 flex flex-row items-center gap-2 w-fit">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 18-6-6 6-6"/></svg>
          Back to Home
        </Link>
        
        <h1 className="text-4xl text-white font-medium mb-4">Privacy Policy</h1>
        <p className="text-zinc-500 mb-12">Last updated: March 17, 2026</p>

        <div className="space-y-12 leading-relaxed">
          {/* Interpretation and Definitions */}
          <section className="space-y-6">
            <h2 className="text-2xl text-white font-medium">1. Interpretation and Definitions</h2>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Interpretation</h3>
              <p>The words whose initial letters are capitalised have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            </div>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Definitions</h3>
              <p className="mb-4">For the purposes of this Privacy Policy:</p>
              <ul className="list-disc pl-6 space-y-3 text-zinc-400">
                <li><strong className="text-zinc-200 font-medium">Company</strong> — referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy, refers to Hitarth Nayak, operating as an independent UI/UX & Graphic Designer.</li>
                <li><strong className="text-zinc-200 font-medium">Cookies</strong> — small files placed on Your computer, mobile device or any other device by a website, containing details of Your browsing activity on that website among its many uses.</li>
                <li><strong className="text-zinc-200 font-medium">Country</strong> — refers to India.</li>
                <li><strong className="text-zinc-200 font-medium">Device</strong> — any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                <li><strong className="text-zinc-200 font-medium">Personal Data</strong> — any information that relates to an identified or identifiable individual.</li>
                <li><strong className="text-zinc-200 font-medium">Service</strong> — refers to the Website.</li>
                <li><strong className="text-zinc-200 font-medium">Usage Data</strong> — data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong className="text-zinc-200 font-medium">Website</strong> — refers to Hitarth Nayak's portfolio, accessible from hitarthnayak.com</li>
                <li><strong className="text-zinc-200 font-medium">You</strong> — the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </div>
          </section>

          {/* Collection, Cookies and Usage */}
          <section className="space-y-6">
            <h2 className="text-2xl text-white font-medium">2. Collection, Cookies and Usage</h2>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Personal Data</h3>
              <p className="mb-4">When You submit a contact form on Our Website, We collect the following personally identifiable information:</p>
              <ul className="list-disc pl-6 space-y-2 text-zinc-400 mb-4">
                <li>First name and last name</li>
                <li>Email address</li>
                <li>Enquiry type</li>
                <li>Message content</li>
              </ul>
              <p>By submitting the contact form, You confirm that You have read and agree to this Privacy Policy. We will only use the information You provide to respond to Your enquiry and to discuss potential design projects or collaborations.</p>
            </div>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Usage Data</h3>
              <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of Our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            </div>

            <div>
              <h3 className="text-xl text-white font-medium mb-3">Tracking Technologies & Cookies</h3>
              <p className="mb-4">We use Cookies and similar tracking technologies to track activity on Our Service and store certain information. The technologies We use may include:</p>
              <ul className="list-disc pl-6 space-y-3 text-zinc-400 mb-6">
                <li><strong className="text-zinc-200 font-medium">Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of Our Service.</li>
                <li><strong className="text-zinc-200 font-medium">Web Beacons.</strong> Certain sections of Our Service may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages and for other related website statistics.</li>
              </ul>
              
              <p className="mb-4">We use the following Cookies on Our Website:</p>
              <div className="space-y-4">
                <div className="bg-white/5 p-5 rounded-xl border border-white/10">
                  <h4 className="text-zinc-200 font-medium mb-1">Necessary / Essential Cookies</h4>
                  <p className="text-sm text-zinc-500 mb-3">Type: Session Cookies | Administered by: Us</p>
                  <p className="text-sm">Purpose: Essential to provide You with services available through the Website and to enable You to use its features.</p>
                </div>
                <div className="bg-white/5 p-5 rounded-xl border border-white/10">
                  <h4 className="text-zinc-200 font-medium mb-1">Analytics Cookies</h4>
                  <p className="text-sm text-zinc-500 mb-3">Type: Persistent Cookies | Administered by: Third-party analytics providers</p>
                  <p className="text-sm">Purpose: These Cookies collect information about how visitors use Our Website to help Us improve the Service.</p>
                </div>
              </div>
            </div>
          </section>

          {/* Retention, Security and Transfers */}
          <section className="space-y-6">
            <h2 className="text-2xl text-white font-medium">3. Retention, Security and Transfers</h2>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Retention of Your Personal Data</h3>
              <p className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We apply the following retention periods:</p>
              <ul className="list-disc pl-6 space-y-3 text-zinc-400 mb-4">
                <li><strong className="text-zinc-200 font-medium">Contact Form Submissions</strong> — Form data (name, email, enquiry type, message): retained for up to 24 months from the date of submission to allow Us to handle follow-up correspondence regarding design projects.</li>
                <li><strong className="text-zinc-200 font-medium">Usage Data</strong> — Website analytics data: up to 24 months from the date of collection.</li>
              </ul>
              <p>When retention periods expire, We securely delete or anonymise Personal Data.</p>
            </div>

            <div>
              <h3 className="text-xl text-white font-medium mb-3">Security of Your Personal Data</h3>
              <p>The security of Your Personal Data is important to Us. Whilst We strive to use commercially reasonable means to protect Your Personal Data, no method of transmission over the Internet or method of electronic storage is 100% secure, and We cannot guarantee its absolute security.</p>
            </div>
          </section>

          {/* Disclosure, Rights and Compliance */}
          <section className="space-y-6">
            <h2 className="text-2xl text-white font-medium">4. Disclosure, Rights and Compliance</h2>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Your Right to Delete Your Personal Data</h3>
              <p>You have the right to request that We delete the Personal Data that We have collected about You. To make such a request, please contact Us using the details at the bottom of this page.</p>
            </div>

            <div>
              <h3 className="text-xl text-white font-medium mb-3">Law Enforcement</h3>
              <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
            </div>

            <div>
              <h3 className="text-xl text-white font-medium mb-3">Other Legal Requirements</h3>
              <p className="mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
              <ul className="list-disc pl-6 space-y-2 text-zinc-400 mb-6">
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Company</li>
                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>Protect the personal safety of users of the Service or the public</li>
                <li>Protect against legal liability</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Children's Privacy</h3>
              <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us so that We can take steps to remove that information from Our systems.</p>
            </div>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Links to Other Websites</h3>
              <p>Our Service may contain links to other websites that are not operated by Us. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
            </div>
          </section>

          {/* Tools and Services We Use */}
          <section className="space-y-6">
            <h2 className="text-2xl text-white font-medium">5. Tools and Services We Use</h2>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Vercel</h3>
              <p>Our Website is hosted on Vercel, Inc. Vercel may collect certain technical data such as IP addresses and request logs for the purpose of delivering and securing the Service. For more information, please review Vercel's Privacy Policy.</p>
            </div>

            <div>
              <h3 className="text-xl text-white font-medium mb-3">Analytics</h3>
              <p>If analytics are added in the future, this section will be updated to reflect the specific tool used and the data it collects.</p>
            </div>
          </section>

          {/* Policy Changes and Contact */}
          <section className="space-y-6">
            <h2 className="text-2xl text-white font-medium">6. Policy Changes and Contact</h2>
            
            <div>
              <h3 className="text-xl text-white font-medium mb-3">Keeping You Updated</h3>
              <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this Privacy Policy periodically for any changes.</p>
            </div>

            <div>
              <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
              <ul className="list-disc pl-6 space-y-3 text-zinc-400">
                <li><strong className="text-zinc-200">By email:</strong> <a href="mailto:freelancing.hitarth@gmail.com" className="hover:text-white transition-colors underline decoration-white/20 underline-offset-4">freelancing.hitarth@gmail.com</a></li>
                <li><strong className="text-zinc-200">By visiting this page on our website:</strong> <span className="italic">COMING SOON!</span></li>
              </ul>
            </div>
          </section>
        </div>
      </div>
    </main>
  );
}
